apiVersion: apps/v1
kind: Deployment
metadata:
  name: bel-idri-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bel-idri-app
  template:
    metadata:
      labels:
        app: bel-idri-app
    spec:
      containers:
        - name: bel-idri
          image: bilalelidrissi171/bel-idri:v1
          ports:
            - containerPort: 8888
      env:
        - name: APP_NAME
          value: "app"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: bel-idri-service
  namespace: dev
spec:
  selector:
    app: bel-idri-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bel-idri-ingress
  namespace: dev
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bel-idri-service
                port:
                  number: 80
